name: FMCAS scheduled processor

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes; adjust as needed

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm install
      - name: Run processor
        run: node gh_processor.js --delay=300
      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: fmcsa-results
          path: output/*.csv
